### ISSUE TITLE
React router auth flow 

### ISSUE THREAD

**Issue by harisvsulaiman** [meteor/react-packages#102]
React router on enter hook cannot be used to redirect to login view (if the user isn't logged in using meteor.user() state)

**Comment by eXon** [comment]
The login redirect is easier to do if you use a parent route that take care of this. I use componentDidMount because the SSR will fail otherwise. Example:

```javascript
AppRoutes = (
  <Route component={App}>
    <Route component={AuthApp}>
      <Route path="login" component={Login} />
      <Route path="register" component={Register} />
      <Route path="forgot" component={ForgotPassword} />
      <Route path="reset/:token" component={ResetPassword} />
    </Route>
    <Route component={RestrictedApp}>
      <Route component={Dashboard} />
    </Route>
  </Route>
);

 RestrictedApp = React.createClass({
  propTypes: {
    children: React.PropTypes.node.isRequired
  },

  contextTypes: {
    router: React.PropTypes.object.isRequired
  },

  componentDidMount() {
    if (!Meteor.userId()) {
      this.context.router.transitionTo('/login');
    }
  },

  render() {
    if (!Meteor.userId()) {
      return null;
    }

    return React.addons.cloneWithProps(this.props.children);
  }
});
```

**Comment by stubailo** [comment]
I also think that redirecting to a login URL is an anti-pattern that can often result in the app losing track of what URL the user was originally trying to go to. I would just do an if statement in your top-level component that renders a login screen instead of doing it in the router.

Either way, I don't think this is an issue specific to this repo.

**Comment by harisvsulaiman** [comment]
Thank you!
