### ISSUE TITLE
'reactjs/react-meteor' vs 'meteor/react-packages'

### ISSUE THREAD

**Issue by artin-phares** [meteor/react-packages#103]
I'm just started looking into React - Meteor marriage. Immediately found this two repos.  
And can't find any discussion on following simple questions:
- what is the reason of having this second package?
- am I right that both created pretty much for the same purpose?
- what are particular differences?
- and key one depending on previous: what should I chose for next project?

**Comment by stubailo** [comment]
Hey, this is a totally legit question!

@benjamn wrote the other package, and he's working at Meteor now. You can think of this as the next generation version. We're working together to deprecate reactjs:react in concert with the release of Meteor 1.2 which will have this more official integration.

I think you should choose this package because it will be the one being maintained and supported for the foreseeable future.

**Comment by artin-phares** [comment]
Nice. Fully convinced now.
Thank you.
