### ISSUE TITLE
Template helper a step back?

### ISSUE THREAD

**Issue by colvint** [meteor/react-packages#106]
Existing React Meteor packages seem to provide a cleaner way to use React components in templates. For example, [react-meteor](https://github.com/reactjs/react-meteor/blob/42a61f3ef76861b728c6e35dd865e5af3b046181/src/ReactMeteor.js#L149) supports a `templateName` property which lets you do:

```javascript
React.createClass({
  templateName: 'FooComponent',
  render: function () {
    return (<div>awesome!</div>);
  }
});
```

```html
{{> FooComponent}}
```

The template helper introduces several intermediate steps to get the same result. Any reason the above approach doesn't work?

**Comment by stubailo** [comment]
We want to move as far as possible away from assuming that things are global variables. The template helper approach means that you don't need to make all of your React components global to be able to use them with Blaze.

If you want, you can easily write a community package that will re-add the functionality you want, but we explicitly decided not to do it in the official one because we don't think this is a good pattern.
