### ISSUE TITLE
What's next for React + Meteor 1.3

### ISSUE THREAD

**Issue by yyx990803** [meteor/react-packages#169]
With the ES2015 modules being enabled in Meteor 1.3, we are planning to recommend a new, better workflow for working with React in Meteor. Here's the outline:

## Direct npm installs

Users now are encouraged to install React directly from npm using `npm install react react-dom` (and any additional addons needed) instead of `meteor add react`.
  
#### Benefits of this approach:
  
  - The current `react-runtime` packages require manual updates to stay up-to-date with React’s frequent release schedule. When installing directly from NPM, users can easily select the specific version of React and the specific list of React addons they want to use.
    
  - It is now much easier to work with 3rd party npm packages that expect React to exist as a peer dependency and directly `require(‘react’)`  in their code. Previously we had to use a Browserify-based hack to replace these.

#### Potential issues:
  
  - Backwards compatibility with old packages or apps that depend on `react-runtime`. Luckily as of release [`1.3-modules-beta.5`](https://github.com/meteor/meteor/issues/5788#issuecomment-174621057), packages can now directly import top-level `node_modules` in an app. The new `react-runtime` package would simply be setting the global `React` by using the npm installed version. If React is not installed from npm, there would be a warning prompting you to do so.

## Meteor Data Integration

The community has been looking for a new pattern to use instead of the mixin approach used by `react-meteor-data`, especially now that ES2015 is the default language, we don't want Meteor's default data integration to block users from using the class-based React component syntax.

There is a lot of community innovation going on in this space, e.g. Arunoda’s work on Mantra. [MDG is also working on major improvements to Meteor's data layer](http://info.meteor.com/blog/reactive-graphql). At this very moment, the absolute best practice is yet to be defined. So for now what we are going to provide is a minimal addition to the current `react-meteor-data` package, essentially a higher-order-component based on the current `ReactMeteorData` mixin:

``` js
import React from 'react';

ReactMeteorDataContainer = function (Component, getMeteorData) {
  return React.createClass({
    mixins: [ReactMeteorData],
    getMeteorData() {
      return getMeteorData(this.props);
    },
    render() {
      return <Component {...this.props} {...this.data} />
    }
  });
};
```

And with modules, an example component using this function:

``` js
import React from 'react';
import { Meteor } from 'meteor/meteor';
import { Todos } from '../lib/collections';
import { ReactMeteorDataContainer } from 'meteor/react-meteor-data';

// The app component is "pure" and only depend on props
export class App extends React.Component {
  render() {
    return (
      <div>
        <h1>App!</h1>
        <p>{ this.props.loading ? 'loading...' : '' }</p>
        <ul>
          {this.props.todos.map((todo, i) => {
            return <li key={i}>{ todo.text }</li>
          })}
        </ul>
      </div>
    )
  }
};

// The "container" simply wraps the app component and feeds data to it as props.
export const AppContainer = ReactMeteorDataContainer(App, () => {
  const handle = Meteor.subscribe('todos');
  return {
    loading: !handle.ready(),
    todos: Todos.find().fetch()
  };
});
```

This pattern goes along with the ideas discussed in [Presentational and Container Components](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0#.mjvm5qt97) and [Let's Compose some React Containers](https://voice.kadira.io/let-s-compose-some-react-containers-3b91b6d9b7c8#.u0q8oqrd0). The main benefit is that the presentational/dumb/pure components can be individually imported in tests and easily tested because they only depend on props. It also makes refactoring easier because the rendering logic and the data management logic is decoupled.

In addition, very often the pure version can be further simplified to a stateless functional component:

``` js
export const App = ({ loading, todos }) => (
  <div>
    <h1>App!</h1>
    <p>{ loading ? 'loading...' : '' }</p>
    <ul>
      {todos.map((todo, i) => {
        return <li key={i}>{ todo.text }</li>
      })}
    </ul>
  </div>
);
```

The container syntax is not set in stone, so any suggestions/concerns are welcome. We are working on an example app (equivalent of [meteor/todos](https://github.com/meteor/todos) but for React) using Meteor 1.3 and the npm-based workflow, and will be adding the updated React integration docs as a new chapter to the Meteor Guide.

**Comment by arunoda** [comment]
Awesome. Glad to see going away from mixins. That's the way to go. I have a suggestion.
With [react-komposer](https://github.com/kadirahq/react-komposer) we already have the Tracker integration and works pretty well.

Of course we follow a similar API and integration some other data sources. And it's loaded from NPM.

So, shall we use instead and I'm open to change the API if needed.

**What are the benefits.**

* Since GraphQL is coming, we don't how the client will be, so it'll be better to use the same tool(or same pattern) to use them.
* We can use same tool, if your decided to fetch some other client side stuff
* Getting it from NPM means, this can be used outside of Meteor and may be open to some Meteor mobile integration.
* We allow to return a function, which is runs when the component unmounted, so you can do some cleanup task if needed. (This is very usual sometimes, using it in Mantra)

Just a suggestion.

**Comment by nata-g** [comment]
I agree with @arunoda . From developer perspective it becomes so much easier to reason with if   there is one common implementation standard. Since both essentially have the same conceptual basis.

**Comment by yyx990803** [comment]
@arunoda I've definitely thought about it - my main consideration is for users migrating from codebases currently using `react-meteor-data`, so I am trying to keep the compose function API consistent with the old `getMeteorData` function. Is there any particular reason `composeWithTracker` uses a callback based API?

**Comment by nata-g** [comment]
Suggestion:: If migrating the existing codebases is the issue why don't react-komposer api be changed to expose react-meteor-data mixin as well. In that way there is only one module to go to and it takes care of all cases. My .02 cents

**Comment by arunoda** [comment]
Hey awesome you liked it. Here's why we use a callback. 

## Callback 

Sometimes when we load the data we need to cleanup some stuff. This is related to clearing some global state. 

That's what you return as function. It follows the all the composer APIs. This is pretty useful and used in Mantra based apps. 

## Error Handling & Loading

This is something we always too. But don't need to copy these in every UI component unless we wanted. 

That's what react-composer accepts and error message and a data object. 
User can customize these error and loading components as needed. 
This saves our tinkering a lot. 

> I am open to some better API. If we have. 

## Migration 

Easy, just like you did with this suggested API, you can import it from NPM instead. 

If someone using FlowRouter, we published a new project called react-mounter which does the job of ReactLayout. It's tested used by few guys we know. 

## Unit Testing

Using npm helps us to unit test composers pretty easily. Otherwise you need do some hack or isolate composer code. That's because npm does not know how to load meteor packages. 

## Performance 

There are some work we need to do to improve performance and rerunning composer functions everytime. So, once we did it we can use it for all. 

## Future

Currently we use Tracker. But later on we can use something. But then also the change surface is very minimal. 
And we already know how to plug them.

**Comment by faceyspacey** [comment]
The interface @luisherranz is suggesting with his Transparent Reactive Programming solution, "Trux," might be worth checking out:  

https://github.com/worona/trux

It's also combining a TRP interface with the the *higher order component* DX.

**Comment by faceyspacey** [comment]
also, why not Tracker React as a higher order component instead? 

https://github.com/ultimatejs/tracker-react

guess it's time for me to make that upgrade.

**Comment by deejross** [comment]
I personally prefer @arunoda's react-komposer simply because it's already pluggable and able to use multiple data sources. The cleanup callback is nice too. I would hope there would be a way to make it backwards compatible with the react-meteor-data package, but let's face it: backwards compatibility went out the window already so developers are going to have to rewrite stuff anyways.

**Comment by yched** [comment]
The ReactMeteorDataContainer HOC proposed in the original post above will not work for wrapping components that also need to use props passed by the parent, not just props returned by the getMeteorData function.

It seems this line in ReactMeteorDataContainer 
```js
 return <Component {...this.data} />
```

should rather be :
```js
 return <Component {...this.props} {...this.data} />
```
?

**Comment by yyx990803** [comment]
@arunoda thanks for the explanation, I think that makes a quite convincing case! I think I will use `react-komposer` in the test app and most likely we will recommend it in the guide.

@yched good catch - yes it should pass down the props.

**Comment by arunoda** [comment]
@yyx990803 That's awesome. Let me know if you need any kind of API change. 
I am happy to work on that.

**Comment by stubailo** [comment]
Personally I think react-komposer's extreme flexibility also makes it much more difficult and configuration-heavy to use, and require developers to be comfortable with multiple higher-order functions. IMO the API could be made slightly less flexible with the benefit of being a lot more friendly. Perhaps I'm the only one?

**Comment by arunoda** [comment]
@stubailo actually it's not sashko. You only need it to fetch data. 
Then for any other stuff you can use the UI component. 

Like any lifecycle stuff, animations. 

Even, working with multiple higher order components is pretty easy and useful when used to react style.

**Comment by nata-g** [comment]
or maybe the documentation should be made more better and user friendly to benefit people migrating in to React world....

**Comment by arunoda** [comment]
@nata-g don't worry. We have a plan for that. We will launch a course on React. 
Then you will be a React Guru under 2 hours.  
It will land here: https://tutor.mantrajs.com

So, no need any migration. Just build apps like the way it should be done in React.

**Comment by nata-g** [comment]
Awesome @arunoda . Looking forward to it. I like  the sound of it -  React Guru :smile:

**Comment by ChrisCinelli** [comment]
Would Meteor 1.3 with React be able to do server side rendering ?

**Comment by arunoda** [comment]
@ChrisCinelli SSR is something goes outside or Meteor. This is closely goes with the Router.
For the FlowRouter and ReactRouter there are two SSR projects.

Here's the [flow-router](https://github.com/kadirahq/flow-router/tree/ssr) version. Currently, it's not working for Meteor 1.3. 
But we are planning to do it soon.

**Comment by huttonr** [comment]
Here's what I've thrown together and have been using in the interim.

https://github.com/huttonr/react-meteor-computations

It may provide some interesting ideas for handling Tracker reactivity in React.

Can also discuss this particular solution [in this forum post](https://forums.meteor.com/t/alternative-to-reactmeteordata-mixin/17161).

**Comment by yched** [comment]
> @ChrisCinelli SSR is something goes outside or Meteor. This is closely goes with the Router.
For the FlowRouter and ReactRouter there are two SSR projects.
Here's the [flow-router](https://github.com/kadirahq/flow-router/tree/ssr) version. Currently, it's not working for Meteor 1.3. 
But we are planning to do it soon.

And for react-router there's the [meteor react-router-ssr package](https://atmospherejs.com/reactrouter/react-router-ssr) that works great.
The only drawback is that it currently relies on the atmosphere wrapper packages for react and react-router rather directly on the the npm libs, but @eXon is planning to change that for Meteor 1.3

**Comment by dagatsoin** [comment]
I have just tried @arunoda react-komposer and it works great.

I also use react-redux. And there is a function called `connect` which generate a higher-order-component for connecting the unique store of redux to the dumb components.

So I use react-komposer to conenct Meteor to React and react-redux to connect redux to react. Here is an exemple:
```
const DumbComp = ({objects}) => (<span>I have {objects.length} in my chest</span>)

const komposerFunction = (props, onData) => {
  const handler = Meteor.subscribe('mapObjects');
  if(handler.ready()) {
    const objects = MapObjects.find().fetch();
    console.log(objects);
    onData(null, {objects});
  } else {
    onData(null, null);
  }
};
const AwareOfMeteorComp= composeWithTracker(komposerFunction)(DumbComp);

const getVisibleObjects = (objects, filters)=> {
  return objects.filter(object => _.contains(filters, object.category));
};

// this is executed at each new state change
const mapStateToProps = (state, ownProps) => {
  return {
    objects: getVisibleObjects(
      ownProps.objects,
      state.mapReducers.mapFiltersReducer
    )
  };
}
AwareOfMeteorAndReduxComp = connect(mapStateToProps)(AwareOfMeteorComp);
```

But it seems a lot of boilerplate for me. Is there a way to optimize this?

**Comment by arunoda** [comment]
Okay. Here react-komposer part is pretty straight forward. 
Other code if for the redux. You always need to do that. 
I suggest you to move this into react-komposer repo where we can discuss more. 
Let's keep this thread clean.

**Comment by Jpunt** [comment]
I'm a proponent of @yyx990803's take on this. react-komposer is interesting, but a bit separated from how the rest of the world (in react/flux) doing things. It's a big part of Mantra I guess, but that's "just" one take on building an app right?

I think the biggest pain-point in building an app in meteor+react is where the border lies between those two. @yyx990803's higher order component makes that very clear, I think react-komposer/mantra is making that a bit too abstract (with all due respect @arunoda).

**Comment by arunoda** [comment]
@Jpunt react-komposer was not built for Mantra. It takes ideas from react-redux directly and generalized it. Also this is the same pattern used in Relay. It's a tool to generate higher order components :)

**Comment by arunoda** [comment]
I wrote an article on this topic and some examples. Check my blog post:

[Using Meteor Data and React with Meteor 1.3](https://voice.kadira.io/using-meteor-data-and-react-with-meteor-1-3-13cb0935dedb#.xssad52qp)

Here I talk about some of the most asked questions when using react-komposer.

**Comment by markoshust** [comment]
@arunoda thank you for the article. I sort of understood it before, but not really. This clarified a lot.

FYI, I would update the example in your README. I think that it is throwing a lot of people off because it appears overly verbose. I'd even remove the `const` assignment there to simplify it further.

In the README:
```
const Time = ({time}) => (<div>Time is: {time}</div>);
const composerFunction = (props, onData) => {
  const handler = Meteor.subscribe('serverTime');
  if(handler.ready()) {
    const {time} = ServerTimeCollection.findOne();
    onData(null, {time});
  } else {
    onData(null, null);
  }
};

// Note the use of composeWithTracker
const Clock = composeWithTracker(composerFunction)(Time);
```

This example is a lot easier to understand for someone coming from `ReactMeteorData` mixin usage:

```
import {composeWithTracker} from 'react-komposer';
import PostList from '../components/post_list.jsx';

function composer(props, onData) {
  if (Meteor.subscribe('posts').ready()) {
    const posts = Posts.find({}, {sort: {_id: 1}}).fetch();
    onData(null, {posts});
  };
};

export default composeWithTracker(composer)(PostList);
```

I think moving the main component to a separate file is actually easier to understand, because it represents a real-life example and is more compartmentalized. I think using standard collection usage (collection.find().fetch()) also will help others 'get it'. Now, with this example, it's easy to understand and implement, whereas before I wasn't quite sure what is going on.

**Comment by arunoda** [comment]
@markoshust Yeah! That's a good suggestion. Will do it now.

**Comment by sebakerckhof** [comment]
While this is a discussion on react, I think the idea of Presentational and Container Components is good and could therefore also be recommended in your guides on angular if you recommend this for React.

You could easily create a controller that loads data, some presentational directives/components and combine them into container directives/components. A bit like:
```js
myModule.controller('postContainerCtrl',postContainerCtrl);
postContainerCtrl.$inject = [$scope,$reactive];
function postContainerCtrl($scope,$reactive){
  $reactive(this).attach($scope);
  this.helpers({
   posts : () => Posts.find({});
  });
  this.loading = true;
  this.subscribe('posts',()=>[],()=>{this.loading = false;});
}

//Purely presentation component
myModule.component('postList', {
  bindings: {
    loading: '=',
    posts: '='
  },
  controller:function(){...},
  controllerAs:'vm',
  template: `
    <ul>
        <li ng-repeat="post in vm.posts track by post._id">{post.title}</li>
    </ul>
    `
});

//Now combine them as you like into containers. 
myModule.component('postListContainer', {
  bindings: { },
  controller:'postContainerCtrl',
  controllerAs:'container',
  template: `
    <post-list loading="container.loading" posts="container.posts"></post-list>
    `
});
```

**Comment by Jpunt** [comment]
While the example from @markoshust is a lot more clear, I'm still on the fence on this one. When composing instead of wrapping, how would you render such a component? In this case a 'PostList'?

I also can't find an example with a full react-class, not just the dumbed down version as a closure. Is that still possible with komposer?

That said, I'm kinda bumped that this issue was opened with great news and exciting stuff, but then got sidetracked to this. @yyx990803's wrapper is a tiny step for people familiar with ReactMeteorData (almost everyone who's learning React since it came to meteor) and a lot better than the mixin. I don't think we should derail the community into a drastically different way of doing these things, imho. Again, it could be great as "a way", but that shouldn't mean it's "the way" from Meteor's point of view.

**Comment by stubailo** [comment]
@sebakerckhof note that the Meteor guide recommends the same for Blaze: http://guide.meteor.com/ui-ux.html#components

**Comment by roberto68** [comment]
ok so container is just the way data is fetched from meteor and for React "internals" I can use Redux right?  and when react (user) triggers request - there's an action for that in redux store and it calls some function which writes to the DB (meteor methods) and then changed datas are fetched via that container?

**Comment by dagatsoin** [comment]
@roberto68 I think you are in the same case as me Meteor/React/Redux
It seems we need a little boilerplate to work with both with nested higer order components.
See https://github.com/kadirahq/react-komposer/issues/20

**Comment by roberto68** [comment]
I saw this but I  mean the "meteor way" ReactMeteorDataContainer, but I may also play with komposer a bit

**Comment by leonidez** [comment]
@yyx990803 What about creating an es6 class that includes the ReactMeteorData functionality?

For example:

```
class DataComponent extends React.Component {}

_(ReactMeteorData).keys().forEach(key => {
  DataComponent.prototype[key] = ReactMeteorData[key]
})
```

Then when we need to create container components we can just:

```
class ListViewContainer extends DataComponent {
  getMeteorData (){
    return {
      todos: Todos.find().fetch()
    }
  }
  render (){
    const {todos} = this.data
    return (
      <ListView list={todos} />
    )
  }
}

```

I think this pattern would come closer to the links you reference regarding container and presentational components.

**Comment by huttonr** [comment]
@leonidez There are a few implementations of this sort of thing.

https://github.com/brigand/react-mixin
http://blog.jamiter.com/2016/01/28/es6-classes-with-react-mixin-meteor-1-3/

**Comment by deejross** [comment]
That's what I was going to try at first, but it sounds like a more official solution (which could be very different) is on the way. I'm still using Blaze and waiting for the React + Meteor stuff to settle down a bit before trying to make the switch. 






On Mon, Feb 1, 2016 at 12:35 PM -0800, "huttonr" <notifications@github.com> wrote:












@leonidez There are a few implementations of this sort of thing.



https://github.com/brigand/react-mixin

http://blog.jamiter.com/2016/01/28/es6-classes-with-react-mixin-meteor-1-3/

**Comment by Lenin7** [comment]
http://blog.jamiter.com/2016/01/28/es6-classes-with-react-mixin-meteor-1-3/

es6: Cannot read property 'find' of undefined.

**Comment by lvdo** [comment]
We built this with Meteor + React: https://configurator.mazda.nl/ (sorry, Dutch only, but you get the idea)
During the project with 5 fulltime devs we ran into two issues with the React integration:

1. Bugs due to confusion between `getMeteorData`/`this.data` and `this.props` to get data external to the component, particularly the order in which they trigger `render`. If we only use `getMeteorData` to query our collections in a few contained components, it is fine, but when we throw `Tracker` and `ReactiveVars` in the mix, we quickly ended up with a situation where components were rerendered up to 10x after each user input. 
2. Performance issues due to React eager rerendering. We ended up writing a lot of `shouldComponentUpdates` that seemed a bit superfluous. For instance the case when a list is changed, you'd like to only render updates.

To solve this we wrote this package: https://github.com/Q42/autovars
Demo of point 2 here: http://autovars-table.meteor.com/

Here is the autovars implementation of the simple todos app: https://github.com/Q42/autovars/blob/master/examples/simple-todos-autovars/App.jsx

Autovars effectively replaces `getMeteorData` and `getInitialState` with `constructAutoVars` which is executed once before mount and which should return a hash with functions that are `autorun` based on their Tracker dependencies. Reading from an autovar in `render` will also create a Tracker dependency and trigger an update on change. Owning all those executing functions, Autovars will cancel executing functions when dependencies have changed in the meanwhile, skipping to the latest state.

I don't think many people will run into the same issues we did, but our solution helped us create much faster, a lot easier to maintain code. Probably some of you can point out where we went wrong and how we could have solved these issues in the frameworks present. But maybe our perspective helps in ongoing discussions about Meteor + React.

(BTW I'm a fan of the component composition pattern, but 6 months ago when we started this development mixins were the only practical approach)

**Comment by yyx990803** [comment]
@lvdo thanks for the insights, this is really helpful. I will take a look at Autovar and see if there's anything we can incorporate into the recommended pattern. My hunch is that there's room for similar perf improvements when using the higher order component pattern.

**Comment by arunoda** [comment]
@yyx990803 Actually talking about performance issues, I did some stuff recently.

Now react-komposer has a built in `shouldComponentUpdate` hook and it's pure.
See: https://github.com/kadirahq/react-komposer/blob/master/lib/index.js#L53

**Comment by lvdo** [comment]
@yyx990803 @arunoda I'd say the Autovar improvements could probably be combined with the higher order component pattern and Arunoda's work on react-komposer. What can I do to help?

**Comment by GeoffreyBooth** [comment]
@yyx990803, with these improvements how would a CoffeeScript or [CJSX](https://atmospherejs.com/jhartma/cjsx) coder use Meteor Data with React? CoffeeScript has its own `class` that isn’t equivalent to ES2015’s `class`, and at the moment it doesn’t support `import`/`export` at all (though [they’re working on it](https://github.com/jashkenas/coffeescript/issues/4078)). Would you keep the mixin around as an alternative?

See also [this thread](https://github.com/meteor/react-packages/issues/6).

**Comment by deejross** [comment]
I would imagine it would be up to CoffeeScript to introduce ES6 output support. Mixin support is deprecated by React and could be removed at any time.  This proposal would (if I'm understanding correctly) use react-komposer as the basis or Meteor+React integration which is implemented much differently than it is now, making the mixin unnecessary. 

Besides all that, react-komposer uses functions instead of classes to make dumb components, then a separate function that gets called reactively to set this.props within the dumb component. So you may not even need to use classes at all.

**Comment by arunoda** [comment]
@deejross one correcttion.

`react-komposer` does not force you to use **functional stateless components** all the times. Sometimes, we need to use a  React lifecycle hook or deal with DOM events. Then it's a good place to create React Component class with extending `React.Component`.

**Comment by deejross** [comment]
@arunoda I forgot about that use case. In that instance, CoffeeScript I think would have to support ES6 classes. I've never used CoffeeScript before, so I can't say for certain, but it sounds like CoffeeScript support would be an issue until they are able to work with ES6 classes.

**Comment by yyx990803** [comment]
@GeoffreyBooth the mixin is of course going to be kept for backwards compatibility! I'm not familiar with CJSX, but if it can compile some sort of module syntax down to CommonJS exports, then it should work with the module system in 1.3 (we are just compiling ES2015 module syntax down to CommonJS as well, then they are executed at runtime with [install.js](https://github.com/benjamn/install)). You will have to rely on its maintainers willing to implement that though.

**Comment by yyx990803** [comment]
@lvdo looking at Autovar's code, it seems it's doing a shallow comparison for the props to prevent over-rendering? Is that essentially the same with pureRenderMixin? (I believe that is also essentially what @arunoda has implemented for `react-komposer`). Correct me if I am wrong.

**Comment by lvdo** [comment]
@yyx990803 That is correct, shallow prop comparison is similar to `pureRenderMixin` and allows for passing of ReactiveVars as props without causing renders. 

However Autovars combines several techniques:
- shallow prop comparison to allow ReactiveVars to be passed down the component hierarchy without triggering renders along the way. 
- logic in pure functions so execution order and frequency can be controlled by Autovars.
- async rendering and execution of logic to block the browser for shorter periods
- trigger render only when a ReactiveVar is read (`.get()`) not when it is referenced.

Consider this scenario: a user event triggers 40 components to update, then after 10 are updated, another user event triggers the same 40 components to be updated. In plain React the rendering would be synchronous, blocking the user events until all 40 components are rendered, only to rerender after the next input event is handled. With Autovars, the browser is not blocked, so the event can be handled and the remaining 30 components moved to the end of the update queue so they get rerendered once with the final state.

**Comment by AnnotatedJS** [comment]
@yyx990803 Is the solution as presented in the original post still relevant?

**Comment by yyx990803** [comment]
@AnnotatedJS it is.

And also some update for @arunoda: after experimenting with it, we feel that while `react-komposer` offers a lot of flexibility, it is a bit too low level and the very functional API can be confusing to users who are not used to that style. If we want to change that it probably involves pretty fundamental API changes.

As of now I am experimenting with an API that is similar to what was originally proposed in this issue, but with a bit more room for other options. What's interesting is that it is just an API sugar layer: while the API can be totally identical, the underlying implementation can be based either on `react-meteor-data` or `react-komposer`.

To see what I mean by that, here is an example app built using the latest 1.3 beta and React: https://github.com/meteor/module-todos-react - in particular there are two helpers that offers the identical `createContainer` API but using `react-meteor-data` and `react-komposer`, respectively: https://github.com/meteor/module-todos-react/tree/master/imports/ui/helpers

And this is how it's used: https://github.com/meteor/module-todos-react/blob/master/imports/ui/containers/AppContainer.jsx

In common use cases, this helper makes connecting a component with meteor data very straightforward (and very close to the old `react-meteor-data` usage). In cases where working with other types of data source is necessary, the user can then further compose the container with `react-komposer`.

**Comment by yched** [comment]
May I suggest to swap the order of arguments from   
`reactMeteorDataContainer(wrappedComponent, getMeteorDataFn)`
to  
`reactMeteorDataContainer(getMeteorDataFn, wrappedComponent)` ?

`(wrapper, wrapped)` seems more intuitive than `(wrapped, wrapper)` and AFAICT is more common for "higher-order-component" helpers, notably because it lends itself to being currified (for instance using [recompose](https://github.com/acdlite/recompose)'s createHelper()) and used as an ES6 @decorator :
```
@reactMeteorDataContainer(getMeteorDataFn)
class Component extends React.Component {
...
```

When the component is inlined, it also provide a reading order more consistent with the actual execution logic :
```
 const MongoFetcher = meteorData(
  // First, collect reactive data from props 
  ({ id }) => ({doc: MyCollection.findOne(id)}),
  // Then the component receives that data as props
  ({ doc }) => doc ? <div>{doc.title}</div> : <div>Loading</div>
);
```

**Comment by AnnotatedJS** [comment]
I have just uploaded commit 7 of my [Meteor-React-Start-App](https://github.com/AnnotatedJS/meteor-react-start-app).
It uses Meteor 1.3 beta5, React and React Router. I have used the react-mixin solution and so far, so good. It is up-and-running at [meteor.com](http://meteor-react-start-app.meteor.com/)

@yyx990803 I have looked at the code of https://github.com/meteor/module-todos-react and will install it tomorrow at my windows development environment.

**Comment by yyx990803** [comment]
@yched good points! Love the second example.

**Comment by arunoda** [comment]
@yyx990803 Yeah! That's good with me too.

**Comment by D1no** [comment]
Guys, TrackerReact is now updated for Meteor 1.3 and allows for very easy compositions of reactive components. I.e. 'class MyReactApp extend TrackerReact(React.Component)'. Also as mixin or decorator

https://github.com/ultimatejs/tracker-react#example

Not elegant, but here a quick repo to try for now.
https://github.com/D1no/TrackerReact-Meteor1.3

- clone/fork/download
- npm install
- meteor update --release 1.3-modules-beta.11
- meteor

in web console

Mongo.Collection.get("tasks").insert({title: "Test Title", text: "A dummy text."});
Everything works fine. (Before modules did not go well together with the old package export and mixin structure).

**Comment by queso** [comment]
@d1no: I like it. I can say after spending two weeks with react-komposer, TrackerReact feels like a more much 'Meteor'-like solution.

Would love to hear @yyx990803 thoughts on it.

**Comment by queso** [comment]
Also, @D1no, why not handle the stopping of subscription more automatically than it currently does? Seems strange to not make the componentWillUnmount stuff more automatic and similar to how template level subscriptions work now with Blaze and subscriptions.

**Comment by D1no** [comment]
Yes, react-komposer is great, but from my experience not well suited for quick prototypes and when building out for complicated production use-cases, it was replaced with redux - or similar event sourcer - anyway. But TrackerReact should get one very very far.

Regarding subscription magic: I get ask that a lot and I am simply not sure if it's a good idea to tie subscriptions to the life cycle of one particular component...again. Like it was done with blaze templates. 

Though it seems that a data subscription is tied to one components lifecycle - in many cases i.e. with apps that gradually transition to react - you often find multiple react instances that don't share a common react component. Are "not pure" yet but require the same data. Or would benefit to share subscriptions via a react context. Sharing and handling subscriptions via state seems to be a good practice here?

Leading to my perspective: Data-subscriptions are a separate entity which life cycle you should handle in a declarative fashion. Preventing an accidental stop and re-start of subscriptions (that means re-running everything(!)), be passed around like props to allow them to be handed outside of react (blaze, jquery, webworker messenger etc.). But most importantly, being aware of them (just like Collections). 

*But I am open to arguments*: Similar to getMeteorData we could look for them, but probably better, provide some sort of TrackerReact subscription method.

**Comment by queso** [comment]
> Perhaps I'm the only one?

@stubailo you aren't the only one that thinks that, I agree with you on this.

**Comment by D1no** [comment]
I added a wholistic implementation example for TrackerReact here:
https://github.com/D1no/TrackerReact-Example

@queso @stubailo I think this provides a lower and better barrier of entry for any vanilla react developers. More than often I heard that "there is no time to take a look at meteor". Given that meteor can be quick replacement for firebase, parse or app engine; configuration should be the last thing to get something on the screen.

**Comment by queso** [comment]
@tmeasday, @zol, or @stubailo - What is this status on this effort since I heard that @yyx990803 is no longer working for MDG. I think the original goal of supporting React from NPM is still pretty vital to moving forward here and guidance from MDG would be helpful since lots of options seem to be popping up in the absence of something official from MDG.

**Comment by stubailo** [comment]
@queso I think @tmeasday is on it now!

**Comment by tmeasday** [comment]
@queso - this is just a draft but you can read about how I think it will work https://github.com/meteor/guide/blob/react-content/content/react.md

You can comment on the PR here: https://github.com/meteor/guide/pull/256/files

Basically I am running with the vision that @yyx990803 laid out above.

**Comment by queso** [comment]
All, looks like the guide has been updated with new advice on the package @tmeasday is working on. Not sure why, I didn't get a ping for the associated issue from 3 days ago via this thread. This update seems darn close to React-Komposer.

I'm still a big fan of sticking to plain ole' JSX for my containers and will likely keep using Tracker-React myself, but figure others might want to take a peek: http://guide.meteor.com/v1.3/react.html#using-createContainer.

**Comment by tmeasday** [comment]
I think we'll hopefully publish beta versions of the various React packages soon (once we do the next 1.3 beta) until then it's kind of difficult to test that stuff..

**Comment by D1no** [comment]
👍 no stress. As soon we are in release/rc, just acknowledge that there is more than one way to get around on reactivity. Depending from which side one comes, some ways are easier to grasp than others.

**Comment by AnnotatedJS** [comment]
I agree with D1no and at the same time I hope you will declare an 'official way' and make that comprehensible with good documentation and some non-trivial examples.

**Comment by abhiaiyer91** [comment]
Yo where did we end up on all this? Started off with Steam now it seems you guys should just save the time and money and write guide articles about TrackerReact and reactKomposer

**Comment by tmeasday** [comment]
@abhiaiyer91 - just published a beta `0.2.6-beta.16` of `react-meteor-data` which includes a `createContainer()` function, which is more or less as documented here: http://guide.meteor.com/v1.3/react.html#livedata

It uses the old `ReactMeteorData` under the hood, although equally it could use `komposer` or (probably) `TrackerReact`, I've just gone with the first for basically conservative reasons (the devil you know and all that).

@D1no I'm not really sure what difference it makes in technically how `createContainer` is implemented (if we are talking about best practice in usage).

I'm not sure I'm following what you are saying here completely, and I'll reply to the forum post but I'm not saying people shouldn't use TrackerReact, just that we it's not the guide-recommended way to do it.

**Comment by ChrisCinelli** [comment]
@tmeasday - I tried to install `react-meteor-data@0.2.6-beta.16` but it was not successful: 

```
 /.meteor/packages/meteor-tool/.1.1.13-beta.16.vdu3t2++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160311-22:31:12.075(-8)? (STDERR) 						throw(ex);
W20160311-22:31:12.075(-8)? (STDERR) 						      ^
W20160311-22:31:12.088(-8)? (STDERR) Error: Can't find npm module 'react-addons-pure-render-mixin'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
```

**Comment by bitsuns** [comment]
@ChrisCinelli ditto for that extra dependency. I wasn't expecting that either, but fortunately the error message was helpful.

**Comment by D1no** [comment]
@tmeasday hey, its not my goal to confuse you. `getMeteorData` is a clunky implementation - analog to the medium article meteor on fb just posted. But that's it. 

I really don't want to waste your time on this any longer. There are much more important construction sites, such as [*testing*](https://github.com/meteor/guide/blob/testing-modules-content/content/testing.md) (which btw, your work I love so far).

If possible, placeholder in the guide a link-reference to TrackerReact as a lightweight alternative to compose a reactive container without any dependencies. In time, I'll just update the examples to a proposed container-based best practice example (similar to the medium post). Thanks for your effords!

**Comment by stubailo** [comment]
This new stuff has shipped.

**Comment by cellog** [comment]
Coming at this from Meteor 1.2, I have to say the createContainer() function literally made no sense to me, even after reading all the docs.  Primarily because the problem is unclear, and none of the react guides show the problem or use it.  In addition, the PostsListsPage identifier is never actually defined anywhere and seems to be magically created by the createContainer() call.  In addition, coming from the MeteorData mixin, it is a complete shift in mentality, and the docs do not stress this at all, just linking to a few articles about container components.

I didn't really get it until I read the docs for react-komposer, which to be honest, feels more meteor-ish to me.  I do think there should be a make-it-and-go way to do this for rapid prototyping, probably by extending React.Component and having it check the class for properties to pull in, etc., but the default way is MUCH cleaner and expresses the problem better than any of the existing docs, even with the occasional grammar oddness.

my 2 cents.

**Comment by stubailo** [comment]
I'd suggest filing this as an issue on the Meteor Guide to improve the documentation there, rather than posting on a closed GitHub thread.

**Comment by cellog** [comment]
Sure, if it were a documentation problem :). I am suggesting the solution the MDG went with is wrong. react-komposer is much easier to understand and use than createContainer

On Tue, Apr 05, 2016 at 4:31 PM, Sashko Stubailo < notifications@github.com [notifications@github.com] > wrote:
I'd suggest filing this as an issue on the Meteor Guide to improve the documentation there, rather than posting on a closed GitHub thread.

**Comment by stubailo** [comment]
I'm sure everyone has a different preference, and you are welcome to use react-komposer if you think that's the best way.
