### ISSUE TITLE
React without a Meteor mixin

### ISSUE THREAD

**Issue by ccorcos** [meteor/react-packages#17]
Hey dude, I'd love to hear your thoughts on this post I wrote:

https://forums.meteor.com/t/react-without-react-mixins/6013

**Comment by stubailo** [comment]
Hey, this looks like a great approach. We want people to try out lots of different things and see what works. That's why all of the packages are split up, so you can use just the JSX transformer, or just the React library, etc.

The `getMeteorData` API we have now seems to be the closest to the possible future `observe` side-loading API, so we thought it made sense for a first attempt. If you want to load all of your data in a root component, you can also do that with the mixin.

One question: I don't see anything in that post about using data from collections - where do you do that?

**Comment by ccorcos** [comment]
So I like to manage subscribing and observing from the same place. I've created a class that effectively allows you to start and stop subscriptions (caching them if you want), and observe as many cursors as you want all in the same place. 

So suppose you are on some page and you click a button to go to some other page, perhaps a list page. You might call a function like `transitionToListPage` your react component.

```coffee
    sub = createSubscription 5, 
      subscribe: (listId, onReady) ->
        Meteor.subscribe('list', listId, onReady)
      startLoading: () ->
        evolveState list: {loading: true}
        render()
      stopLoading: () ->
        evolveState list: {loading false}
        render()
      cursors:
        items: 
          cursor: (listId) -> Items.find({listId})
          added: (id, fields) ->
            evolveState list: append(merge({_id:id}, fields}))
            render()
          changed: (id, fields) ->
             evolveState list: evolveWhere({_id:id}, fields})
            render()
          removed: (id) ->
             evolveState list: dropWhere({_id:id})
            render()
        list:
          cursor: (listId) -> Lists.find(listId, {limit:1})
          added: (id, fields) ->
            evolveState list: title: fields.title
            render()
          changed: (id, fields) ->
            if fields.title
              evolveState list: title: fields.title
              render()
          removed: (id) ->
            transitionToHome()

transitionToListPage = (listId) ->
  sub.start(listId)
  evolveState
    route: 'list'
    list:
      items: Items.find().fetch()
  render()
```

If the list page subscription didnt take any arugments, it would be just as easy to start and stop the subscription in componentWillMount and unmount. At the very least, its nice to stop the subscription in componentWillUnmount.

**Comment by stubailo** [comment]
This is pretty interesting! Let's keep talking on the forums.
