### ISSUE TITLE
ReactMeteorData Redux Provider like Apollo does it

### ISSUE THREAD

**Issue by pawelphilipczyk** [meteor/react-packages#190]
Hi, 

I'm looking at the Apollostack and compare it with the ReactMeteorData createContainer approach. 
I understand the current example is more general for sure as it does not require usage of Redux if someone doesn't want to so I'm just thinking of enhancement not replacement. 

What I'm thinking about is creating something similar to ApolloProvider, let's call it MeteorProvider and then have enhanced connect function to provide access to Meteor data inside Redux store. 

Do you think that this is a good idea?
Is this something that maybe you would consider worth doing too given you're clearly happy with the Redux?

**Comment by stubailo** [comment]
@pawelphilipczyk I think the best way to do this would be to set up something that replaces Minimongo with Redux, uses regular `connect`, and then doesn't use Tracker at all. The main reason we have a special `connect` in Apollo is because the data needs to be transformed into the shape of the query before the component can use it, but that's not really a problem with Mongo data.

Also, the main reason we integrate with Redux `connect` in Apollo is that the update cycle is the same since Apollo data is actually stored in Redux. So I think it's not good to have one container that fetches data from data sources that update in different intervals.

**Comment by pawelphilipczyk** [comment]
I was hoping to get answer from you @stubailo :)

I get what you're saying about the connect function but I'm not sure If I get the part about replacing Minimongo with Redux entirely. What I was thinking is a way to have Meteor subscriptions that update the store by dispatching standard Redux actions so that all components connected to the Redux store refresh but don't need to know where the data came from. To the connected component that would only look like `store.getState().meteor.someData`.

So I agree I could still use the regular connect function from Redux. I would only need to find a nice way to have my Meteor data pushed to Redux store in single place and keep it updated reactively. Maybe this is excactly something I can achieve right now using `createContainer` from `ReactMeteorData` without any modifications.
