### ISSUE TITLE
Change log disappeared? 

### ISSUE THREAD

**Issue by brendonlamb** [meteor/react-packages#294]
We've recently updated this package from `2.0.1` to `2.1.1` and have encountered some strange react timing issues... I'd like to be doing stuff as vanilla / proper as possible but with no change log i'm in the dark. :(

If it's possible to resurrect the change log here and/or present any changes that may not be backwards compatible?

FWIW, the atmosphere page links to a since deleted change log in this repo:
https://atmospherejs.com/meteor/react-meteor-data
https://github.com/meteor/react-packages/blob/master/CHANGELOG.md

**Comment by CaptainN** [comment]
@brendonlamb I'd love to hear more about those timing issues. One of the changes we implemented was a more conservative initial-render computation invalidation algorithm to support "strict mode" rendering (and get ready for concurrent rendering). This will almost certainly cause your computation to be run more often in some cases (in first render, then again when the render is "committed" or `useEffect` is run).

I'm curious to know how this might be effecting you, since I'm working on an update to support Suspense, which may solve this problem in a different way.

**Comment by CaptainN** [comment]
The changelog is here: https://github.com/meteor/react-packages/blob/master/packages/react-meteor-data/CHANGELOG.md

**Comment by CaptainN** [comment]
We recently released `2.2.1` which does address some rare edge cases having to do with subscriptions. I'd love to hear if that had any effect on your usage. I'm going to close this ticket, but if you'd still like, feel free to comment or reopen.
