### ISSUE TITLE
Package to compile templates into React components

### ISSUE THREAD

**Issue by stubailo** [meteor/react-packages#32]
@timbrandin has a good start here: https://atmospherejs.com/timbrandin/jsx-templating

**Comment by stubailo** [comment]
@timbrandin let's keep talking here.

Personally, I would prefer a more React-style API, so that you get all of the normal React stuff except with templates, like this:

```html
<template name="myReactTemplate">
  <div class="hello">
    <mui.RaisedButton onClick={this.buttonClicked} />
  </div>
</template>
```

```js
var MyReactComponent = React.createClass({
  buttonClicked() {
    alert("hello world!");
  },
  render() {
    return ReactTemplate.myReactTemplate;
  }
});
```

What do you think of this? I would also use `componentWillMount`, `componentDidMount`, etc instead of renamed callbacks. Basically, I think it would be best if it was as close to React as possible, so that we don't hide the implementation too much and when people run into bugs it's obvious what is going on. And when people use React tutorials they are going to refer to the React lifecycle callbacks, event handling, etc.

This is just my personal opinion, I'm interested to see what other people think.

**Comment by timbrandin** [comment]
That's an interesting approach, though I like the simplicity of defining "event class" selectors for events and helpers with the Template API as well as getting away from the overhead of defining "React.createClass".

**Comment by timbrandin** [comment]
I guess the issue here is, are we trying to get React developers starting with Meteor or Meteor developers getting an easier transition to React templates.

The reason why I would transition to React from the beginning is due to the fact that it's the only rendering framework that can do server-side rendering and therefor help me in the agenda of in the future finally stop using Drupal, Wordpress (or any other CMS that's cachable). 

We need [Server-side rendering](https://trello.com/c/Lz07fBAm/7-server-side-rendering) and [Incremental Loading](https://trello.com/c/24s6vyxo/55-incremental-loading) for Blaze in Meteor!

Btw, except for the use-case of CMS sites transitioning to apps I see a lot of apps that have a short time-cycle, and in that regard I would see them also having a need for faster page loads which could be handled using Server-side rendering.

**Comment by stubailo** [comment]
> Meteor developers getting an easier transition to React components.

I think this is definitely the goal, but I don't think it will be possible to achieve a situation where everyone's code works with no changes between Blaze and React with templates. People are bound to run into React-specific bugs, and in that case it would be great to be able to look at the React documentation/stack overflow to figure out what is going on.

I guess my perspective was that most people like React's component model and way of defining classes, and just not everyone like JSX. But I guess that's just my opinion, so it might be good to give people a choice between different component definition APIs (as long as they are all still compatible with each other, it doesn't really matter which you use).

**Comment by AdamBrodzinski** [comment]
I'm sure this has been thought of but have you considered Blaze 2.0 using React under the hood but sugared use the Blaze syntax? Having a major version bump would take care of API differences with the current Blaze.

I'm thinking the separate file approach would appeal to a lot of people who would otherwise discount React. This could even create more interest in Meteor, especially if this Blaze 2.0 could be used outside of Meteor (though why would you want to do that? :smile: )

Advantages being that it helps MDG use the same codebase-ish for the view layer if you decided to focus primarily on React and a sugared Blaze 2.0.

**Comment by tmeasday** [comment]
There have been many many many discussions on this topic :)

Closing this I think.
