### ISSUE TITLE
Coffeescript JSX

### ISSUE THREAD

**Issue by zimt28** [meteor/react-packages#6]
It would be great if using the `coffeescript` package would allow to use coffeescript with JSX syntax as well, like `.cjsx`. There are already [transformation tools on GitHub](https://github.com/jsdf/coffee-react-transform/blob/master/README.md).

**Comment by stubailo** [comment]
I encourage you to create your own JSX package that uses that transformer! You can see all of the code for the one we made here: https://github.com/meteor/react-packages/blob/master/jsx/jsx-plugin.js

It should be pretty simple to modify it to work with coffeescript!

I suspect that this will not be a priority for us right now, because there doesn't seem to be a huge market of people using CS + JSX.

**Comment by zimt28** [comment]
Doesn't look any complicated so I'll just have try! Thanks for your response

**Comment by stubailo** [comment]
Reopened because I've heard a few more people ask about this.

**Comment by robertpitt** [comment]
Just a thought, is this something that we might see more often, if so my thoughts are passing a compiled source into the next compiler.

Example:

```
application.jsx.coffee
            |   ^ --------------- First pass through coffee compiler
            ^ ------------------- Second pass though the jsx compiler
```

My initial concerns is weather there would be more use cases.

**Comment by stubailo** [comment]
This might be possible with some of the work currently being done on build plugins.

But at the end of the day, are there so many combinations of different file formats? I feel like it might be OK to just have a separate plugin for each (as long as the actual JSX and CS compilation is factored out, and the build plugin is just a shell that applies them in the right order).

**Comment by ccorcos** [comment]
As requested ;)

https://github.com/ccorcos/meteor-cjsx

**Comment by macrozone** [comment]
@ccorcos :+1: 
awesome! love the cjsx-syntax!

**Comment by stubailo** [comment]
@ccorcos awesome - when we release this, I'm going to add a list of community stuff, will put this on there. Thanks!

**Comment by ccorcos** [comment]
Sounds good. Let me know how I can help!

P.S. I'm starting to reconsider data mixins again, lol!

**Comment by fungilation** [comment]
+1 cjsx! Such pretty syntax :)

@ccorcos, your package mentions `meteor add react-runtime`. Is that not the same/compatible with MDG's official https://atmospherejs.com/meteor/react package?

PS. both react packages are published by MDG, I'm a little confused which should we use... @stubailo?

**Comment by stubailo** [comment]
@fungilation if you look at the guide here: http://react-in-meteor.readthedocs.org/en/latest/#adding-individual-packages

`react` is the package that includes JSX, ReactMeteorData mixin, and the library itself; `react-runtime` is just the React library without any bells and whistles.

If you use both, you still just get one copy of React, of course, because the dependencies are resolved properly.

Is there a better way we could explain this in the guide?

**Comment by stubailo** [comment]
Oh, I have a good idea for this, will push an update to the guide soon.

**Comment by stubailo** [comment]
@fungilation is this clearer? http://react-in-meteor.readthedocs.org/en/latest/#whats-in-the-box

**Comment by fungilation** [comment]
Ya, thanks! And for your cjsx vs jhartma's?

**Comment by ccorcos** [comment]
seems to be about the same

**Comment by timothyarmes** [comment]
Now i just need a sublime text syntax highlighter for CJFX...

**Comment by ccorcos** [comment]
atom has one. 

honestly, I just use straight coffeescript like this:

```coffee
{div} = React.DOM

(div {className: 'something'}, 
  (div {className: 'child1')
  (div {className: 'child2'}))

```

**Comment by macrozone** [comment]
@timothyarmes there is one, looks quite well. Check out the package list.

**Comment by timothyarmes** [comment]
I did check the list, but I can't see one. What's it called?

**Comment by filipenevola** [comment]
I'm closing this just because it's too old. We can open new issues for items that are still valid.
