### ISSUE TITLE
Calling setState inside getMeteorData can result in infinite loop

### ISSUE THREAD

**Issue by timothyarmes** [meteor/react-packages#71]
Overtime the state object changes getMeteorData() is reactively rerun, even though it doesn't depend on state. Since state tends to change a lot, that's not great.

Also, my getMeteorData() needs to set state, which causes an infinite loop if I'm not very careful.

Is this the expected behaviour?

**Comment by stubailo** [comment]
We made `getMeteorData` depend on `state` so that you could filter collections based on state variables. The only output from `getMeteorData` should be the data it returns.

Possibly there is a different way of doing what you are doing - why are you setting a `state` variable from inside `getMeteorData`?

**Comment by timothyarmes** [comment]
Hi,

You can see the code here:

https://github.com/meteor-utilities/avatar/blob/master/react/avatar.jsx

Essentially, when the user object changes I need to change the `state` to update the UI accordingly (changing the avatar image's URL).

This change might result in a error if the URL does not exists. If so an `onerror` callback is used to change the `state` and hide the image.

Now, you might suggest that everything that I've put into `state` could instead be put into `data` instead, however assigning to `data` isn't reactive, so my `onerror`callback wouldn't function. Besides, this stuff really is `state`, it's not data.

Suggestions? As it is it does work.

**Comment by stubailo** [comment]
I think that component shouldn't be using `state` at all.

> // If the URL has changed then we ned to update the state with the new URL

You should just return the url as part of `data`. I think this code should be restructured to avoid doing inline asynchronous stuff inside the component if possible. Also, what does `Avatar.getUrl(user);` do? Isn't `Avatar` the component itself?

Possible what you actually need is two components: one that gets the data, and then passes it down into another component which actually handles the displaying of the avatar.

**Comment by timothyarmes** [comment]
I'm new to React, so I'm open to suggestions. However, if I don't use state then how can I dynamically hide the image of the image URL isn't found?

**Comment by avital** [comment]
@timothyarmes here's what you do -- you use `getMeteorData` as you do now, but don't handle rendering or state in that component. instead, you pass in the data as "props" into a child component. then the child component can use `componentWillReceiveProps` to set state whenever props (which was the original meteor data) changes. the reason this works is that changing state in the child component won't cause the parent component to re-render hence re-fetch the data.

the error message that will appear in the next version of the mixin will explain this.

**Comment by giantelk** [comment]
@timothyarmes `this.data` is reactive, i.e. in a React Components render() it will trigger DOM updates, check the example on this page:
http://react-in-meteor.readthedocs.org/en/latest/meteor-data

Instead of `this.isMounted()` you can `setState` in `componentWillMount()`. But for your example, `this.data` is reactive. Just Meteor reactive code like `Find()` or `Session.get()`, will not be reactive if used outside of `getMeteorData()`.  

Side note: I use Session.get outside of `getMeteorData()` for stuff that doesn't need to be reactive, i.e. just need to pass state between components once when mounted, like in `componentWillMount()`.

**Comment by onedr0p** [comment]
I'm a little late to this post but I was wondering if we cannot set a state in getMeteorData then how would I notify a user of a change? I am posting here because I also get an infinite loop when trying to set state in getMeteorData.

@stubailo For example, I want to use Collection.observe() or Collection.observeChanges() on a Notification collection. When a new document gets inserted into the database I would like to show a pop-up to the user if it was sent to them. Maybe I am thinking about this is a wrong way? I am new to React and have this working in a Blaze project, but I'm looking to port it to React. Thanks for the help.

**Comment by chmac** [comment]
@onedr0p I think the key is to have 1 component which only retrieves data and passes that data to a child component as `props`. That child component will then be automatically updated every time the data changes, so inside that component, you could show the notification to the user whenever you get new `props`.
