### ISSUE TITLE
Composable Components vs Mixins

### ISSUE THREAD

**Issue by ccorcos** [meteor/react-packages#80]
I've come across an interesting pattern for data in React -- separate data fetching into its own meta-component and pass the results as props to a pure view component. Imagine something like this:

```jsx
<MeteorData
  subscribe={ () => Meteor.subscribe('messages', this.props.roomId) }
  fetch={ () => {messages: Messages.find({roomId:this.props.roomId}).fetch()} }
  render={ ({loading, messages}) => <MessageList loading={loading} messages={messages}/> }/>
```

This pattern allows you to write your views as pure views without concerning the view with data management. I'm just curious what you think about this.

**Comment by stubailo** [comment]
Looks great! Does this use ReactMeteorData internally?

**Comment by ccorcos** [comment]
No, I've actually implemented it a little bit differently because I'm using it with any-db. But its pretty simple. It looks like you could do it like this:

```jsx
MeteorData = React.createClass({
  mixins: [ReactMeteorData],
  getMeteorData() {
    const sub = this.props.subscribe()
    const data = this.props.fetch()
    data.loading = !sub.ready()
    return data;
  },
  render() {
    this.props.render(this.data)
  }
})
```

**Comment by ccorcos** [comment]
I just thought it was a neat idea -- maybe of interest

**Comment by stubailo** [comment]
Sure! I'd love to discuss it more, you don't have to close it.

**Comment by ccorcos** [comment]
Well lets discuss! what do you think?

**Comment by stubailo** [comment]
I think it's a great idea, and a perfect way to use getMeteorData in a way that makes your app more maintainable. IMO splitting up components into ones that manage data and ones that just render UI is good.

**Comment by gdub01** [comment]
This is awesome. Thanks! It's like FB's Relay without worrying about graphql. It looks like Meteor can adhere to the relay principles out of the box.

**Comment by ccorcos** [comment]
thats the idea! :+1:

**Comment by ccorcos** [comment]
I refactored any-db today to support ordered and unordered cursors and collections. I also built an abstraction inspired by flux -- a "store" represents both a publication and a subscription. And in the end, it works really nice with composable components :) Here's a chatroom example app:

https://github.com/ccorcos/meteor-any-db/blob/v2/packages/ccorcos:any-db-stores/examples/ddp/main.coffee

let me know waht you think

**Comment by giantelk** [comment]
@ccorcos Looks cool, but what about using this pattern with `react-router`, I'd have to do this in my Route: `handler={MeteorData}`, which kinda confuses things as I want to think of routes rendering views not data. Maybe it's just a matter of thinking about this differently, but what if I have 2 different routes I want MeteorData to render depending on my app logic / user flow? I think frameworks like RoR allow that.

**Comment by ccorcos** [comment]
@giantelk you'd still want a top-level view like `<MessageView>`, but the first child would be `<MeteorData>` with the appropriate props, rendering a `<MessageList>` component with the data.

**Comment by giantelk** [comment]
Thanks for za klarity.

**Comment by stubailo** [comment]
@giantelk sometimes what I do is call my components `<MessagesPage>` and have that be just a thin wrapper that loads data. So I have one component per route, but internally they are built up out of reusable components.

**Comment by giantelk** [comment]
Got it. I need to think more in terms of wrappers😅 Using this pattern I'd
have the top level view wrapper. With my MeteorData calling another wrapper
with 3 components (in one of my use cases) doing the core UI rendering.

MessagesPage
    MessagesData
        MsgWrap
            MainMsg
            ReplyMsg
            AnotherThing

**Comment by AdamBrodzinski** [comment]
@stubailo Here's an idea I had on the forums to use a higher order component similar to @ccorcos 's example above. It's basically a function that takes in params and wraps your component with another using the `ReactMeteorData ` mixin (this is based off of how most flux implementations connect you to flux like [this](https://github.com/goatslacker/alt/blob/master/src/utils/connect.js)).

```javascript
let PostsList = React.createClass({
  propTypes: {
    posts: React.PropTypes.object,
    isReady: React.PropTypes.bool,
    increaseLimit: React.PropTypes.func,
  },
  render() {
    return (
      <div>
        {this.props.posts.map(postDoc => {
            <Post {...postDoc} />
        });}
      </div>
    );
  }
})
//
// wrap component with data wrapper
//
PostsList = Meteor.ReactData(PostsList, {
  increaseLimit(limit = 5) {
    this.limit = limit;
  },
  getMeteorData() {
    const sub = Meteor.subscribe('posts', this.limit);
    return {
      isReady: sub.ready(),
      posts: Posts.find().fetch(),
    }
  }
});
```

However I abandoned the idea after having an issue with Tracker and since i'm using redux now I didn't have time to finish it.

**Comment by ndarilek** [comment]
I like the pattern as presented in the article that brought me here better than the version presented here.

https://medium.com/@SamCorcos/meteor-react-design-pattern-mixins-v-composable-components-990a5411e1b7

A couple thoughts, note that I'm new to React so perhaps they're not idiomatic:

 * Could this.props.children be used instead of a separate render function? Or perhaps both, checking for a render prop first and only using this.props.children if it isn't available? I assume ou mght want to separate your interface from the data-loading wrapper so a render function would make sense, but I could also see circumstances where you'll *always* be rendering Meteor data and would rather just bundle the UI in as children.
 * Could the subscribe function return an array of subscriptions, in which case the subsReady equivalent (I forget what it's called in this example) could just be a reduced AND over the sub.ready() values? It's probably best to have a single subscription per component, but I could see cases where you might want several.

**Comment by ccorcos** [comment]
@ndarilek the example here is the same one as in the article.

- adding props to children is awkward. using a function allows you to use whatever names you want. you could just use a high order function wrapper `renderIfData` or something. Or just do this:

`return this.data ? this.props.render(this.data) : false`

- you could definitely do that, you'd just have to code it up!

const subs = this.props.subscribe()
data.loading = !sub.reduce(function(a,b) {return a&&b}, subs, true)

**Comment by ndarilek** [comment]
The example above still uses ReactMeteorData. Perhaps the chat example linked doesn't, haven't looked at that yet.

**Comment by ccorcos** [comment]
oh yeah. well its not that hard to wrap it in an autorun in componentWillMount

**Comment by rclai** [comment]
It appears like [mixins are going to be dead](https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750) and high order components are the way to go, which looks like is what this thread is getting at?

The author is the guy that wrote Redux along with a bunch of the complementary Redux stuff as well as the Webpack React hot loading stuff.

The idea of "connecting" components with these data wrappers looks like the way to go.

**Comment by stubailo** [comment]
Yeah in that case I think `getMeteorData` can be a great API to build your own data-loading components.

**Comment by ccorcos** [comment]
I really like how Redux works with applying a component with props from an external store.

**Comment by rclai** [comment]
So I've been testing this pattern where you create a function that will hook up any React component with Meteor data to be accessible via `props` instead of `data`. This was inspired by the React Redux [`connect` function](https://github.com/rackt/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options). Here's the usage:

```jsx
var component = React.createClass({
  render() {
    return (
      <ul>
        {this.props.todos.map((todo) => {
          return (
            <li>...</li>
          );
        })}
      </ul>
    );
  }
});

var connectWithTodos = connectMeteorData(function (props /*[, context]*/) {
  return {
    loading: !Meteor.subscribe('todos').ready(),
    todos: Todos.find({ completed: props.completed }).fetch()
  }
});

var TodosList = connectWithTodos(component /*[, contextTypesObject]*/);

// You can render it now, and you can even pass it props too
React.render(<TodosList completed={true} />, mountNode);
```

One thing to note is that you can't access the inner component state in `connectMeteorData`, but you can pass in a state handler function as a prop that the inner component state consumes to update the state which will get passed in from the top as a prop. Not sure if being able to access the inner component's state is something I need to handle, but if yes, how would I go about doing it?

Theoretically, if you've been using the Webpack setup with Redux where you `connect` your component to the store using ES2016 decorators (i.e `@connect(...)`), this `connectMeteorData` could also be used as another decorator on top of `@connect` so that your component is not only connected to the Redux store but also to the Meteor reactive data! Then you won't have to worry about using twice the memory storing Meteor data in Redux.

What do you guys think? I was thinking of publishing the `connectMeteorData` as a package but I'm not sure on the name. I initially named it `meteorizeReactComponent`, but I don't think that's accurate because it returns a function.

You can check out what `connectMeteorData` does under the hood [here](https://github.com/rclai/connect-meteor-data/blob/master/connect-meteor-data.jsx).

**Comment by ccorcos** [comment]
looks cool but theres no cleanup. you never stop the subscription / autorun when the component unmounts...

**Comment by rclai** [comment]
There's no need to because `ReactMeteorData` does that for you already under the hood.

**Comment by ccorcos** [comment]
ahhh. you're wrapping it in a component:

https://github.com/rclai/connect-meteor-data/blob/master/connect-meteor-data.jsx#L30

that makes sense.

**Comment by niklasbuschmann** [comment]
+1, like the idea

**Comment by zimt28** [comment]
I also like the idea :+1:  What do you think about the following syntax?
It doesn't look so messy and you can use multiple subscriptions as well as multiple cursors :)

```jsx
patients = {
  subscription: subs.subscribe 'patients', filter
  data: PatientsCollection.find(filter, sort: { createdAt: -1 }).fetch()
}

<MeteorData patients={patients}>
  {function({ patients }) {
    <ListView loaded={patients.loaded} items={patients.data} />
  }}
</MeteorData>
```
And the simple implementation:
```jsx
Component['MeteorData'] = React.createClass({
  mixins: [ReactMeteorData],
  getMeteorData: function() {
    var props = _.omit(this.props, 'children')
    _.each(props, function(prop) {
      prop.loaded = prop.subscription.ready()
    })
    return props
  },
  render: function() {
    this.props.children(this.data)
  }
})
```
I don't know if something like `.map()` exists for objects, if so it could be even more simplified.

**Comment by atlewee** [comment]
This mixin can also be used with ES6 syntax as a "decorator", this way you write code without wrapping in another component.. And not using the meteor-data as a mixin.

Main App Component: (Normal code, not passing components as prop)
```javascript
class App extends React.Component {
    render() {
        return (
            <div>
                <NormalComponent foo="bar"/>
                <SmartComponent/> 
                <PureComponent foo="bar"/>
            </div>
        )
    }
};
```

Create a MeteorData component as standard ES6 component. This will become the "mixin"
```javascript
class MeteorData extends React.Component {
}
```
Copy/paste the code from meteor-data mixin into this and fix it to work as a class.. (remove commas)

Now you can choose when you create a new component if you want it to be normal or have getMeteorData available by extending "MeteorData" instead of "React.Component"
```javascript
class SmartComponent extends MeteorData {
    getMeteorData() {
        return {
            foo: Session.get("foo")
        }
    }
    render() {
        return <div>Foo: {this.data.foo}</div>
    }
}
```
I never make a standard component, its either smart(MeteorData) and picks up global state or dumb(Pure) with props/arguments from a smart component.
I love the new small pure components:
```javascript
PureComponent = (props) => {
    return <div>Foo: {props.foo} </div>
};
```

**Comment by atlewee** [comment]
Why would you use Redux when you have Meteor?
Instead of passing a global state down the component tree as props, why not just read the global State directly in the components?
And why use props and immutable objects and run a check if something needs to update?
Would it not be better to avoid props and state in the components and just let Mongo update only the effected components via MeteorData?
You can use a local minimongo for the non persistant state.. appState = new Mongo.Collection(null)

you can still use it like you use Redux, the components can call events inside a global Event object that will trigger the correct actions and update the State (State.update("module1.view",{foo:"bar"}) and so on.. Time travel and other stuff shlud still be possible if all actions are recorded properly.

I would call this doing React the Meteor way.. Or is this a bad idea? Why?
This way you can forget about all immutable stuff, dont need Redux, there is never gonna be performed a sinlge shouldcomponentupdate... 
MeteorData just updates the components that subscribes to data that have changed....
No mixins. everything is es6 syntax and we use our Meteor methods to update persistant state and Simple mongo api for local non-persistant state.

**Comment by tmeasday** [comment]
This is more or less the approach we've gone with for 1.3
