### ISSUE TITLE
window.React is undefined in browserify-imported file in package

### ISSUE THREAD

**Issue by optilude** [meteor/react-packages#83]
Hi,

This problem is evident in https://github.com/optilude/meteor-react-example, but also in other projects of mine.

On the `master` branch of `meteor-react-example`, I use Meteor 1.1.0.2 and everything works fine.

On the `meteor-upgrade` branch, I've published an attempt to upgrade to Meteor 1.1.0.3. In the process, a number of React-related packages were updated, see https://github.com/optilude/meteor-react-example/commit/1b47ca9c7998056db53a9a571a590da57551928c.

Here, something very strange is happening. When `cosmos:browserify` runs, it attempts to use `exposify` to use `window.React` in a shim for `require('react')`, but `window.React` is undefined!

(I've also tried the `externalify` transform as per the docs, but the problem is the same, `window['React']['require']` fails because `window.React` is undefined; I prefer `exposify` because it can also handle things like jQuery)

`window.React` is _eventually_ defined; I can get to it in the debug console after the (broken) app has rendered, but it's not defined at the time the package is processed.

What's going on here? Should I be changing anything in the package? In my `package.js` I have added `react` as a dependency: https://github.com/optilude/meteor-react-example/blob/meteor-upgrade/packages/app-deps/package.js

**Comment by stubailo** [comment]
I think this is a real bug, we didn't test the use-case where Browserify is used inside a package well enough.

**Comment by optilude** [comment]
So, it *used* to work until I upgraded. You have a reasonable test case if you just compare the behaviour of the `master` and `meteor-upgrade` branches of the `meteor-react-example`.

**Comment by stubailo** [comment]
OK, will do! Thanks.

**Comment by grigio** [comment]
Did you try [this](https://github.com/thereactivestack/meteor-react-router/blob/4127d61718454bbec6c3cdbfe391025f451b502b/react-router.browserify.js#L1-L2) thereactivestack/meteor-react-router had a similar problem lately

**Comment by optilude** [comment]
@grigio - that may just have done it!

I'm still confused as to why this is needed now, after upgrading, but wasn't needed before; it also doesn't appear to be needed for the `jQuery` shim. Accident?

**Comment by optilude** [comment]
Oh, and one other data point: I had the same problem when I changed the `exposify` transform to the `externalify` as per the react-in-meteor docs.

**Comment by optilude** [comment]
@stubailo I just merged to master with @grigio's fix, so you you should now compare the tag `meteor-1.1.0.2` (works, does not require `globals.React` hack in `client.browserify.js`) with `meteor-1.1.0.3` (works, but only after I put the `globals.React` hack into said file.

Martin

**Comment by rozzzly** [comment]
+1 thanks @grigio for the quickfix and certainly @optilude for digging down into the heart of the issue! I've spent the past three days pulling my hair out trying to get [`material-ui`](https://github.com/callemall/material-ui) to load AND work with ssr.

Early on I came across [`ShockiTV/flow-ssr-mui-example`](https://github.com/ShockiTV/flow-ssr-mui-example) which did **exactly** what I wanted to do. His solution was one of the first I tried in the course of this wild goose chase, but I passed it by after implementing his setup because it just wasn't working. From there, I literally went through and experienced every one of the issues that the github community has faced and eventually overcome in trying to get mui and meteor to place nice together-which I've learned was a huge pain in the ass. 

I only just realized a few hours ago that my repository had the latest versions of all the dependencies while his were set before the breaking change-which occurred only a few days ago. That led me here... which didn't exist when I started my search. :cry: 

--

And seeing as I've mentioned @ShockiTV's solution already, here's my fork of [`flow-ssr-mui-example`](https://github.com/rozzzly/flow-ssr-mui-example) I just made so I could create a PR with the fix forit.

---
Hey @optilude I noticed in your previous comment:
>(works, but only after I put the **globals**.React hack into said file.
You accidently added an s. It's `global`. 

Thanks again guys.

**Comment by stubailo** [comment]
OK, I just added an example to the docs about how to use the React browserify options inside a package.

**Comment by tsadykhov** [comment]
I'm running into this issue while trying to browserify ```react-masonry-component```. I'm doing this app-wide, not inside a package. Just to be sure I tried it with the react-todos example and recreated the issue. 

No luck with ```global.React = React;``` or  using ```exposify```

Any ideas?

**Comment by stubailo** [comment]
Can you post the repro? It could be a bug.

**Comment by tsadykhov** [comment]
My mistake, just realized I needed to inject ```React``` in my require call. That fixed it, thanks!
