### ISSUE TITLE
onClick handler not responding to functions declared with ES6 arrow syntax

### ISSUE THREAD

**Issue by purplecones** [meteor/react-packages#85]
Example below that I was able to replicate:
works
```
Login = React.createClass({
  testFunction: function () {
    console.log('Hello');
  },
  render: function () {
    return (
      <div className="ui fluid large teal submit button" onClick={this.testFunction}>Login</div>
    );
  }
});
```

doesn't work
```
Login = React.createClass({
  testFunction: () =>  {
    console.log('Hello');
  },
  render: () => {
    return (
      <div className="ui fluid large teal submit button" onClick={this.testFunction}>Login</div>
    );
  }
});
```

my packages are:
meteor-platform
autopublish
insecure
react
meteorhacks:npm
cosmos:browserify
npm-container
semantic:ui
flemay:less-autoprefixer
react-template-helper
accounts-password

**Comment by stubailo** [comment]
@purplecones I'm going to look into this potential bug, but I think the best practice is to use method shorthand:

```js
Login = React.createClass({
  testFunction() {
    console.log('Hello');
  },
  render: () => {
    return (
      <div className="ui fluid large teal submit button" onClick={this.testFunction}>Login</div>
    );
  }
});
```

Since a lot of React stuff (namely this.state and this.props) relies on you being able to access `this` inside methods, it is probably not a good idea to use arrow functions to define React class methods.

**Comment by purplecones** [comment]
Thanks for the tip, Sashko. I did not know you can do that. 

I think it's the render that is actually causing the issue. I had to replace the arrow function for render as well for it work.
```
Login = React.createClass({
  testFunction() {
    console.log('Hello');
  },
  render: function() {
    return (
      <div className="ui fluid large teal submit button" onClick={this.testFunction}>Login</div>
    );
  }
});
```

**Comment by stubailo** [comment]
Yes, I missed that part!

Arrow functions aren't just a shorthand for regular functions. They actually do something different when defining `this` inside the function, so `this.testFunction` wasn't returning what you expect.

So I guess this isn't actually a bug.

I updated my comment above to the correct code:

```js
Login = React.createClass({
  testFunction() {
    console.log('Hello');
  },
  render() {
    return (
      <div className="ui fluid large teal submit button" onClick={this.testFunction}>Login</div>
    );
  }
});
```

Arrow functions are mostly useful in iterators:

```js
render () {
  return (
    <div>{
      array.map((item) => {
        return <span onClick={this.testFunction}>Hi</span>
      })
    }</div>
  )
}
```

In this case, the arrow function makes `this` refer to the React component rather than the item from inside `map`.

**Comment by purplecones** [comment]
Thanks for the info!

**Comment by lourd** [comment]
Separate but related, looking at your package list you should checkout `grove:less` :smile:
